database:
  url: "jdbc:mysql://localhost:3306/pdm_life"
  username: "pdm_life_user"
  password: "PdM-Life_UsEr"

discord:
  webhook-url: "https://discord.com/api/webhooks/1365902952187039834/CFVRnTCA_rsNM6ZwoX9fa7Hn1A-J7ZMDzokPu8m-90t8Vz8HW2sTymFwPmQAKe5_xYRM"
