name: PlayerDataManager
version: '1.0.0'
main: net.kinoko2k.pdm.PlayerDataManager
api-version: '1.21'
load: STARTUP
authors: [ kinoko1216 ]
description: Utility Tool
website: https://bento.me/kinoko1216
